FROM node:lts-alpine

# Set working directory
RUN mkdir -p /app
WORKDIR /app

# Copy in frontend files
COPY . /app

# Install dependencies, lint (error if fails lint), build, and clean yarn cache to reduce image size
RUN yarn && \
    yarn lint || exit 1

# For documentation to developers - EXPOSE command doesn't actually do anything, but tells what should be made open
EXPOSE 3000

CMD ["yarn", "serve"]
