version: "3.8"
services:
  database:
    image: docker.io/pbbg/database:master
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=database
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  backend:
    image: docker.io/pbbg/backend:master
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/tests"]
  frontend:
    image: docker.io/pbbg/frontend:master
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
  proxy:
    image: docker.io/pbbg/proxy:master
    ports:
      - 80:80
    volumes:
      - ./certs:/etc/letsencrypt
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
  certbot:
    image: ebarault/letsencrypt-autorenew-docker:latest
    environment:
      - LOGFILE=/var/log/letsencrypt/certrenewal.log
      - DEBUG=false
      - STAGING=false
      - DOMAINS=dev.pbbg.com
      - EMAIL=swctholmeso@gmail.com
      - CONCAT=false
      - HEALTH_CHECK_URL=dev.pbbg.com:80
    ports:
      - 443:443
    volumes:
      - ./certs:/certs
      - ./letsencrypt:/etc/letsencrypt
      - ./var_log_letsencrypt:/var/log/letsencrypt
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
      restart_policy:
        condition: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-s", "-L", "--head", "--fail", "-o", "/dev/null", "-w", "'%{http_code}\n'", "--connect-timeout", "3", "--max-time", "5", "http://dev.pbbg.com:80" ]
